# Array Slicing: Accessing Subarrays

## x[start:stop:step]

# One-Dimensional Subarrays

In [1]:
import numpy as np
x1 = np.array([9, 4, 0, 3, 8, 6])
x1

array([9, 4, 0, 3, 8, 6])

In [2]:
x1[:3] # first three elements

array([9, 4, 0])

In [3]:
x1[3:] # elements after index 3

array([3, 8, 6])

In [4]:
x1[1:4] # middle subarray

array([4, 0, 3])

In [5]:
x1[::2] # every second element

array([9, 0, 8])

In [6]:
x1[1::2] # every second element, starting at index 1


array([4, 3, 6])

In [ ]:
x1[::-1]# all elements, reversed

array([6, 8, 3, 0, 4, 9])

In [8]:
x1[4::-2] # every second element from index 4, reversed

array([8, 0, 9])

# Multidimensional Subarrays

In [9]:
x2 = np.array([[3, 1, 3, 7],
               [4, 0, 2, 3],
               [0, 0, 6, 9]])

In [11]:
x2[:2, :3] # first two rows & three columns


array([[3, 1, 3],
       [4, 0, 2]])

In [12]:
x2[:3, ::2] # three rows, every second column

array([[3, 3],
       [4, 2],
       [0, 6]])

In [13]:
 x2[::-1, ::-1] # all rows & columns, reversed

array([[9, 6, 0, 0],
       [3, 2, 0, 4],
       [7, 3, 1, 3]])

In [14]:
x2[:, 0] # first column of x2

array([3, 4, 0])

In [15]:
x2[0, :] # first row of x2

array([3, 1, 3, 7])

In [16]:
x2[0] # equivalent to x2[0, :]

array([3, 1, 3, 7])

# Subarrays as No-Copy Views

In [17]:
print(x2)

[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]


In [18]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 1]
 [4 0]]


In [19]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  1]
 [ 4  0]]


Unlike Python list slices, NumPy array slices are returned as views rather than copies
of the array data. Consider our two-dimensional array from before: