# Reshaping of Arrays

In [2]:
import numpy as np

In [3]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the
reshaped array, and in most cases the reshape method will return a no-copy view of
the initial array

A common reshaping operation is converting a one-dimensional array into a two-
dimensional row or column matrix:

In [4]:
x = np.array([1, 2, 3])
x.reshape((1, 3)) # row vector via reshape

array([[1, 2, 3]])

A convenient shorthand for this is to use np.newaxis in the slicing syntax:

In [5]:
x[np.newaxis, :] # row vector via newaxis

array([[1, 2, 3]])

In [6]:
x[:, np.newaxis] # column vector via newaxis

array([[1],
       [2],
       [3]])